### ISSUE TITLE
make the website more fast, responsive with better SEO

### ISSUE THREAD

**Issue by zelfroster** [hyprwm/hyprland-website#17]
Since the website is a static one, I would suggest using [NextJS](https://nextjs.org).
It has SSG(Static Site Generation) which compiles the code and generates the site on the server itself. And then makes it available for everyone by sending the pre-rendered HTML to their local CDN(Content Delivery Network). So, It is fast.
It is also developer friendly and It makes it easy for optimizing the site's SEO.

**Comment by vaxerski** [comment]
Why? we use express which is pretty lightweight. No framework is needed for a static website. Hell, I'd be for even throwing away express and just writing static html, but Next? why?

**Comment by zelfroster** [comment]
I get the point you are making.
That was just a suggestion and it's upto you.
NextJS comes with many niceties which will only make the site better.

**Comment by vaxerski** [comment]
Just like all js libraries, it "comes with niceties" but affects performance. One does more, one does less, but there is no reason to change this. Everyone has different opinions and in all honesty for a 2 page static website it doesnt matter at all.

**Comment by zelfroster** [comment]
> it "comes with niceties" but affects performance.

That's exactly what I was talking about, It doesn't affect the performance but makes it better.

**Comment by vaxerski** [comment]
yeeah but you have to rewrite the website for no real rason
