### ISSUE TITLE
Deploy statically instead of dynamically

### ISSUE THREAD

**Issue by LeoDog896** [hyprwm/hyprland-website#24]
This can help alleviate some small pains:
- Deployment of the hyprland-website can happen in GitHub Pages's deployment system instead of on some other server (allowing release cycles to happen closer to the website's development, as well as lowering the bar for testing on forks)
  - This also adds the benefit of being able to browse previous artifacts
- Additional post-processing steps (e.g. lightningcss) can be added during compile-time instead of being served in run-time with express

One static site generator I'm particularly fond of is [lume](https://lume.land/), written with the Deno runtime but allows for more advanced generation features in a simple package without overloading new contributors with the need to learn new frameworks or configuration systems (unlike what was suggested in #17).

If you're open to this idea, I'm fully ok with making a PR to refactor the site to use Lume or some other static site generator alternatives such as the more heavier but robust gatsby. Just leave a comment or react appropriately:+1:.

**Comment by vaxerski** [comment]
christ, why.

You make a small landing page for a random project and then a kjhillion people come with their own idiotic frameworks and "new and improved" css languages.

That is precisely why I hate webdev. Can't have a single open source website without hordes of people coming to rewrite everything in something else which adds zero value to it.

And people still ask me why the wiki's backend is closed source.

**Comment by LeoDog896** [comment]
All good! Sorry for the extra clutter in that message - all I really meant was moving it to Github Pages instead of you having to manually deploy it per commit (with the necessity of some preprocessing tool for EJS -> raw assets), but I'm sure you have your reasons :+1:

**Comment by vaxerski** [comment]
I was against using ejs anyways, all my personal websites are written in pure html + css + js.

It really does not matter, it's a small landing page, it's splitting hairs at that point.

And no, we won't move to gh pages.
