### ISSUE TITLE
feat: Slightly increase line height

### ISSUE THREAD

**Issue by willuhmjs** [hyprwm/hyprland-website#25]
Currently, the line-height on the home page is so small that some of the lines touch each other. I suggest slightly increasing the line height. Currently, there is a significant difference in line height between the home page and the wiki pages. While not pictured in my example, you can vertically center the image with the adjacent text content to maintain the alignment. 

Here is an example of what this would look like:

**Before:**
![image](https://user-images.githubusercontent.com/58738637/230748950-4100cbda-1dd9-44b6-9096-08212b084ca5.png)

**1.2em Line Height:**
![image](https://user-images.githubusercontent.com/58738637/230749014-4b24d340-223a-4f47-92de-18f3282dc244.png)

**Comment by vaxerski** [comment]
feel free to mr
