### ISSUE TITLE
Un-styled components

### ISSUE THREAD

**Issue by System-x64** [hyprwm/hyprland-website#3]
Something is going horribly wrong...i removed the "get started_" code from `home.ejs` why is still showing up on site

the logo also is still the svg instead of png

I guess the new code is adding up on top of old ones but ain't removing the old codes,
could u delete all the lines from your hosting server (for both ejs and css) and paste the code from github manually? @vaxerski 

![screenshot_20220928_170135](https://user-images.githubusercontent.com/90208727/192768312-b332a456-b3c9-4cb9-970d-82ec869a731d.png)

**Comment by vaxerski** [comment]
done

**Comment by System-x64** [comment]
Parfait!

![screenshot_20220928_171013](https://user-images.githubusercontent.com/90208727/192769979-0ec84e8e-43f8-46f2-babf-906996910ff4.png)
