### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by storopoli** [hyprwm/hyprland-website#39]
I would love to get a RSS feed for `https://hyprland.org/news`

**Comment by Visual-Dawg** [comment]
Thats a good idea. 
I dont know when I am going to implement it though

Feel free to PR

**Comment by Visual-Dawg** [comment]
I created a PR https://github.com/hyprwm/hyprland-website/pull/42

However, it am not sure if its working properly.
Validators say its valid, but readers dont really pick up on it.
I tried to subscribe to the localhost address, so maybe they dislike that?

This is the generated xml, which can be retrieved on `/rss`.

```xml
<?xml version="1.0" encoding="UTF-8" ?>
    <rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
    <channel>
    <atom:link href="https://hyprland.org/rss" rel="self" type="application/rss+xml" />
    <title>Hyprland News</title>
    <link>https://hyprland.org/news</link>
    <description>Tiling window manager with the looks</description>

    <item>
      <guid isPermaLink="true">https://hyprland.org/news/wallpaperContest</guid>
      <title>We're hosting a Hyprland wallpaper contest!</title>
      <link>https://hyprland.org/news/wallpaperContest</link>
      <pubDate>Sun, 17 Dec 2023 22:36:57 GMT</pubDate>
    </item>
</channel>
</rss>
 ```

Can you take a look? :)

**Comment by storopoli** [comment]
I can confirm it works if you type `hyprland.org` in Feeder (Android).

Thank you so much ❤️
