### ISSUE TITLE
Shouldn't the "Hypractive Development" button open github?

### ISSUE THREAD

**Issue by anotherhadi** [hyprwm/hyprland-website#40]
The "Hypractive Development" button ([Hypractive.svelte](https://github.com/hyprwm/hyprland-website/blob/main/src/routes/Hypractive.svelte)) currently plays a (cool) animation but does not open the Hyprland GitHub repository as expected(?). It feels a bit odd to only get the animation.

Could send a PR if it wasn't the intended behavior.

**Comment by Visual-Dawg** [comment]
Honestly I havnt though about linking to GH issues.
Makes sense though, but how would it work with the easter-egg?

**Comment by Visual-Dawg** [comment]
Maybe, after the animation was unlocked, linking the button to the commits or issues (in the context of hypractive dev the commits seem to make more sense)

**Comment by anotherhadi** [comment]
> Maybe, after the animation was unlocked, linking the button to the commits or issues (in the context of hypractive dev the commits seem to make more sense)

Could be nice!
