### ISSUE TITLE
when clicking on a category other categories unfold

### ISSUE THREAD

**Issue by nnyyxxxx** [hyprwm/hyprland-website#78]
so say i fold every category:
![image](https://github.com/user-attachments/assets/0af2811b-923d-4e85-b1c0-545e9b8bd6ae)
and then i decide i want to click on a category:
![image](https://github.com/user-attachments/assets/8d15c1bb-991f-4f39-9cba-e2ca5aecb007)
the two categories i folded previously: automatically unfold, this needs to be fixed ASAP

**Comment by vaxerski** [comment]
wrong repo... you were in the right one before.
